---
- hosts: localhost

  roles:
    - role: get-vmss-inventory
      vars:
        resource_group_name: "weight-tracker-{{ env }}-rg"


- hosts: scalesethosts
  # become: true

  roles:
    - role: VM-docker-configuration
      vars:
        env: "{{ env }}"
