
   - name: add nodejs apt key
     apt_key:
       url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
       state: present


   - name: add nodejs 14.x repository
     apt_repository:
       repo: deb https://deb.nodesource.com/node_14.x {{ ansible_lsb.codename }} main
       state: present
       update_cache: yes


   - name: install nodejs 14.x
     apt:
       name: nodejs
       state: present

   - name: install unzip
     apt:
       name: unzip
       state: present


   - name: Copy .env to VM web-app folder
     copy:
       src: .env
       dest: /bootcamp-app/


   - name: Copy zipped artifacts and unarchive
     unarchive:
       copy: yes
       src: bootcamp-app.zip
       dest: /bootcamp-app/


   - name: Uninstall modules
     shell: rm -rf node_modules
     args:
       chdir: /bootcamp-app
       executable: /bin/bash


   - name: NPM instll
     community.general.npm:
       path: /bootcamp-app

   - name: Install latest PM2
     shell: sudo npm install pm2@latest -g
     args:
        chdir: /bootcamp-app
        executable: /bin/bash


   - name: Initialize PM2 startup
     shell: |
        sudo pm2 startup
        sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
     args:
        chdir: /bootcamp-app
        executable: /bin/bash


   - name: Delete any previous proccess and initialize database
     shell: |
        pm2 delete all
        npm run initdb 

     args:
        chdir: /bootcamp-app
        executable: /bin/bash


   - name: Start the web application using pm2 and save the process
     shell: |
        sudo pm2 start npm -- run dev
        sudo pm2 save
     args:
        chdir: /bootcamp-app
        executable: /bin/bash